{
  "version": "3.9",
  "volumes": {
    "blog-db": {
      "external": true
    },
    "caddy-data": {
      "external": true
    },
    "caddy-config": null
  },
  "services": {
    "db": {
      "build": "./pg",
      "volumes": [
        "blog-db:/var/lib/postgresql/data"
      ],
      "ports": [
        "3001:5432"
      ],
      "environment": {
        "POSTGRES_USER": "admin",
        "POSTGRES_PASSWORD": "${BLOG_DB_PASSWORD?you must set an admin password}",
        "POSTGRES_DB": "blog"
      }
    },
    "blog": {
      "build": ".",
      "environment": {
        "BLOG_DB_URL": "postgres://server:server@db:5432/blog",
        "BLOG_LISTEN_ADDRESS": "0.0.0.0:8080"
      }
    },
    "proxy": {
      "image": "caddy:2.4.6-alpine",
      "restart": "unless-stopped",
      "ports": [
        "8080:8080",
        "80:80"
      ],
      "volumes": [
        "./Caddyfile:/etc/caddy/Caddyfile",
        "caddy-data:/data",
        "caddy-config:/config"
      ]
    }
  }
}
