CREATE USER server WITH PASSWORD 'server';

GRANT CONNECT ON DATABASE blog TO server;
GRANT USAGE ON SCHEMA public TO server;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO server;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
	GRANT SELECT ON TABLES TO server;
