CREATE USER server WITH PASSWORD 'server';

GRANT CONNECT ON DATABASE blog TO server;
GRANT USAGE ON SCHEMA blog TO server;
GRANT SELECT ON ALL TABLES IN SCHEMA blog TO server;

ALTER DEFAULT PRIVILEGES IN SCHEMA blog
	GRANT SELECT ON TABLES TO server;
