[package]
name = "blog-cli"
version = "0.4.0"
edition = "2021"

[[bin]]
name = "blog"
path = "src/main.rs"

[dependencies]
clap = { version = "3.0.7", features = ["cargo", "env", "unicode", "wrap_help"] }
tokio = { version = "1.15.0", features = ["full"] }
sqlx = { version = "0.5.10", features = ["runtime-tokio-rustls", "postgres", "chrono"] }
url-escape = "0.1.0"
pulldown-cmark = "0.9.0"
anyhow = "1.0.52"
sha2 = "0.10.1"
serde = { version = "1.0.133", features = ["derive"] }
serde_json = "1.0.74"
