{
  "version": "3.9",
  "volumes": {
    "blog-db": null
  },
  "services": {
    "db": {
      "build": "../pg",
      "volumes": [
        "blog-db:/var/lib/postgresql/data"
      ],
      "ports": [
        "3001:5432"
      ],
      "environment": {
        "POSTGRES_USER": "admin",
        "POSTGRES_PASSWORD": "${BLOG_DB_PASSWORD?you must set an admin password}",
        "POSTGRES_DB": "blog"
      }
    },
    "blog": {
      "build": ".",
      "environment": {
        "BLOG_SERVER_DB_URL": "postgres://server:server@db:5432/blog",
        "BLOG_LISTEN_ADDRESS": "0.0.0.0:8080",
        "BLOG_COPYRIGHT_NAME": "${BLOG_COPYRIGHT_NAME-Some Person}",
        "BLOG_URL": "${BLOG_URL?you must set the full site url including the protocol for the rss feed to work; any dummy value is fine}"
      },
      "volumes": [
        "${BLOG_MEDIA_MOUNT?you need to set the bind mount point on your local filesystem for the media uploads to work}:/app/media",
        "../static:/app/static"
      ],
      "ports": [
        "${BLOG_HTTP_PORT-8080}:8080"
      ]
    }
  }
}
