{
  "version": "3.9",
  "volumes": {
    "caddy-data": null,
    "caddy-config": null
  },
  "services": {
    "blog": {
      "build": "..",
      "environment": {
        "BLOG_SERVER_DB_URL": "${BLOG_SERVER_DB_URL?you must set a postgres connection url for the blog}",
        "BLOG_LISTEN_ADDRESS": "0.0.0.0:8080",
        "BLOG_COPYRIGHT_NAME": "${BLOG_COPYRIGHT_NAME?you must specify a copyright name for the blog contents}",
        "BLOG_URL": "${BLOG_URL?you must set a full URL for the blog including the protocol}"
      },
      "volumes": [
        "${BLOG_MEDIA_MOUNT?you need to set the bind mount point on your local filesystem for the media uploads to work}:/app/media"
      ]
    },
    "proxy": {
      "image": "caddy:2.4.6-alpine",
      "restart": "unless-stopped",
      "ports": [
        "${BLOG_PROXY_PORT-8080}:8080"
      ],
      "volumes": [
        "../Caddyfile:/etc/caddy/Caddyfile",
        "caddy-data:/data",
        "caddy-config:/config"
      ],
      "environment": {
        "BLOG_ADDRESS": "${BLOG_ADDRESS?you must set an ip or a domain address for the caddy proxy}"
      }
    }
  }
}
